### PR TITLE
Use more concise syntax in README

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Not sure if this is a positive change but I thought it looked more intuitive.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Yeah, I think that's a good point, actually, considering it's being described as Dict/NamedTuple-like (and those both support `obj[key]` syntax). Should we update the `index.md` too?

**Comment by ali-ramadhan** [comment]
Done! I forgot about the docs lol.

**Comment by charleskawczynski** [comment]
Np, I have mixed feelings about having it in duplicate places. Thanks!

**Pull request merged**
